### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by chkone** [zhangwengame/SGGX-Plugin-for-Mitsuba#2]
Hello,

Is it a missing file:
heterogeneous_sggx.cpp
src\medium\heterogeneous_sggx.cpp(615) : error C2039: 'lookupSGGX' : n'est pas membre de 'mitsuba::VolumeDataSource'
        include\mitsuba/render/volume.h(32) : voir la déclaration de 'mitsuba::VolumeDataSource'
src\medium\heterogeneous_sggx.cpp(671) : error C2039: 'lookupSGGX' : n'est pas membre de 'mitsuba::VolumeDataSource'
        include\mitsuba/render/volume.h(32) : voir la déclaration de 'mitsuba::VolumeDataSource'
src\medium\heterogeneous_sggx.cpp(736) : error C2039: 'lookupSGGX' : n'est pas membre de 'mitsuba::VolumeDataSource'
        include\mitsuba/render/volume.h(32) : voir la déclaration de 'mitsuba::VolumeDataSource'
scons: **\* [build\release\medium\heterogeneous_sggx.obj] Error 2
scons: building terminated because of errors.

On path:
include\mitsuba\render\
Have we a volume.h missing?

Best

**Comment by zhangwengame** [comment]
Yeah, you are right. I am sorry for that and thank you for the notification, I've added the volume.h~

**Comment by chkone** [comment]
Thanks
